server:
  port: 1987

app:
  cors.origins: "http://localhost:1504"
  jwtSecret: "aHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1kUXc0dzlXZ1hjUQ=="
  jwtExpiration: 86400000

spring:
  datasource:
  url: jdbc:postgresql://localhost:5432/documentsdb
  username: dbuser
  password: dbuser
  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
