server:
  port: 1987

app:
  cors.origins: "*"
  phpcaptcheck:
    url: "https://dm-anfrcaptcheckdemo.oceaneconsulting.com"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/efeedback
    username: dbuser
    password: dbuser
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
